/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Delete: typeof import('./components/icons/Delete.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    Explore: typeof import('./components/Explore.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NoImage: typeof import('./components/icons/NoImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Title.vue')['default']
    Uploader: typeof import('./components/Uploader.vue')['default']
    Warn: typeof import('./components/icons/Warn.vue')['default']
  }
}
