/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./components/Canvas.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Delete: typeof import('./components/icons/Delete.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Ex: typeof import('./components/Ex.vue')['default']
    Explore: typeof import('./components/Explore.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NavButton: typeof import('./components/NavButton.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NoImage: typeof import('./components/icons/NoImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Title.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    Uploader: typeof import('./components/Uploader.vue')['default']
    Warn: typeof import('./components/icons/Warn.vue')['default']
    Waterfall: typeof import('./components/Waterfall.vue')['default']
  }
}
